//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AircraftSimManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AircraftSimManager.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert .PTP to .ZIP.
        /// </summary>
        public static string BtnConvertPtpToZip {
            get {
                return ResourceManager.GetString("BtnConvertPtpToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Livery.
        /// </summary>
        public static string BtnRemoveLivery {
            get {
                return ResourceManager.GetString("BtnRemoveLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Title.
        /// </summary>
        public static string BtnSaveTitle {
            get {
                return ResourceManager.GetString("BtnSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tool from the top menu to get started..
        /// </summary>
        public static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Calculator.
        /// </summary>
        public static string FuelCalculatorTitle {
            get {
                return ResourceManager.GetString("FuelCalculatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liveries Manager.
        /// </summary>
        public static string LiveriesManager {
            get {
                return ResourceManager.GetString("LiveriesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tool from the top menu to get started.
        /// </summary>
        public static string MainTextSelectTool {
            get {
                return ResourceManager.GetString("MainTextSelectTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathSim {
            get {
                return ResourceManager.GetString("PathSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Calculator.
        /// </summary>
        public static string PerformanceCalculator {
            get {
                return ResourceManager.GetString("PerformanceCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (BR).
        /// </summary>
        public static string PortugueseBr {
            get {
                return ResourceManager.GetString("PortugueseBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewImage {
            get {
                return ResourceManager.GetString("PreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        public static string SimulatorSelectText {
            get {
                return ResourceManager.GetString("SimulatorSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the .PTP or .ZIP file here to install it.
        /// </summary>
        public static string TextDragFilePtpZip {
            get {
                return ResourceManager.GetString("TextDragFilePtpZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in the simulator.
        /// </summary>
        public static string TextInputTitleSimulator {
            get {
                return ResourceManager.GetString("TextInputTitleSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install / Convert Livery (.PTP / .ZIP).
        /// </summary>
        public static string TextInstallConvertLivery {
            get {
                return ResourceManager.GetString("TextInstallConvertLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Liveries.
        /// </summary>
        public static string TextInstalledLiveries {
            get {
                return ResourceManager.GetString("TextInstalledLiveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview image.
        /// </summary>
        public static string TextNoPreviewImage {
            get {
                return ResourceManager.GetString("TextNoPreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Livery Edition.
        /// </summary>
        public static string TextSelectedLivery {
            get {
                return ResourceManager.GetString("TextSelectedLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
