//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AircraftSimManager.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AircraftSimManager.Shared.Resources.AppResources_pt", typeof(AppResources_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter .PTP para .ZIP.
        /// </summary>
        public static string BtnConvertPtpToZip {
            get {
                return ResourceManager.GetString("BtnConvertPtpToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Textura.
        /// </summary>
        public static string BtnRemoveLivery {
            get {
                return ResourceManager.GetString("BtnRemoveLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Plano de Voo.
        /// </summary>
        public static string BtnSaveFlightPlan {
            get {
                return ResourceManager.GetString("BtnSaveFlightPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Título.
        /// </summary>
        public static string BtnSaveTitle {
            get {
                return ResourceManager.GetString("BtnSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma ferramenta no menu superior para começar..
        /// </summary>
        public static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cálculo automático de distância e distribuição nos tanques da aeronave..
        /// </summary>
        public static string DescTextAutomaticCalcDistance {
            get {
                return ResourceManager.GetString("DescTextAutomaticCalcDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta funcionalidade está em desenvolvimento e será disponibilizada em breve nas próximas atualizações do Aircraft Sim Manager!.
        /// </summary>
        public static string DescTextComingSoon {
            get {
                return ResourceManager.GetString("DescTextComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronize estes tanques diretamente com a aeronave no simulador via SimConnect!.
        /// </summary>
        public static string DescTextPROFeatures {
            get {
                return ResourceManager.GetString("DescTextPROFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao executar extrator PTP: {0}.
        /// </summary>
        public static string ErrorExecutingExtractor {
            get {
                return ResourceManager.GetString("ErrorExecutingExtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na extração (código {0}): {1}.
        /// </summary>
        public static string ErrorExtractionFailed {
            get {
                return ResourceManager.GetString("ErrorExtractionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo .ptp não encontrado.
        /// </summary>
        public static string ErrorPtpNotFound {
            get {
                return ResourceManager.GetString("ErrorPtpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executável PtpUnpack.exe não foi encontrado na pasta Tools/PtpUnpacker..
        /// </summary>
        public static string ErrorUnpackerNotFound {
            get {
                return ResourceManager.GetString("ErrorUnpackerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculadora de Combustível.
        /// </summary>
        public static string FuelCalculatorTitle {
            get {
                return ResourceManager.GetString("FuelCalculatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciador de Texturas.
        /// </summary>
        public static string LiveriesManager {
            get {
                return ResourceManager.GetString("LiveriesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma ferramenta no menu superior para começar.
        /// </summary>
        public static string MainTextSelectTool {
            get {
                return ResourceManager.GetString("MainTextSelectTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho.
        /// </summary>
        public static string PathSim {
            get {
                return ResourceManager.GetString("PathSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculadora de Performance.
        /// </summary>
        public static string PerformanceCalculator {
            get {
                return ResourceManager.GetString("PerformanceCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculadora de Performance.
        /// </summary>
        public static string PerformanceCalculatorTitle {
            get {
                return ResourceManager.GetString("PerformanceCalculatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português (BR).
        /// </summary>
        public static string PortugueseBr {
            get {
                return ResourceManager.GetString("PortugueseBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pré-visualização.
        /// </summary>
        public static string PreviewImage {
            get {
                return ResourceManager.GetString("PreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando descompactação de {0}....
        /// </summary>
        public static string ProgressStartingUnpack {
            get {
                return ResourceManager.GetString("ProgressStartingUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulador.
        /// </summary>
        public static string SimulatorSelectText {
            get {
                return ResourceManager.GetString("SimulatorSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extração concluída com sucesso..
        /// </summary>
        public static string SuccessExtraction {
            get {
                return ResourceManager.GetString("SuccessExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distância Calculada (NM).
        /// </summary>
        public static string TextCalculatedDistance {
            get {
                return ResourceManager.GetString("TextCalculatedDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Breve.
        /// </summary>
        public static string TextComingSoon {
            get {
                return ResourceManager.GetString("TextComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuição nos Tanques.
        /// </summary>
        public static string TextDistributionTanks {
            get {
                return ResourceManager.GetString("TextDistributionTanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arraste o arquivo .PTP ou .ZIP aqui para instalar.
        /// </summary>
        public static string TextDragFilePtpZip {
            get {
                return ResourceManager.GetString("TextDragFilePtpZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanq. Central.
        /// </summary>
        public static string TextDrawCenterTank {
            get {
                return ResourceManager.GetString("TextDrawCenterTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanq. Esquerdo.
        /// </summary>
        public static string TextDrawLeftTank {
            get {
                return ResourceManager.GetString("TextDrawLeftTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanq. Direito.
        /// </summary>
        public static string TextDrawRightTank {
            get {
                return ResourceManager.GetString("TextDrawRightTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota do Voo (ICAO).
        /// </summary>
        public static string TextFlightRoute {
            get {
                return ResourceManager.GetString("TextFlightRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculadora de Combustível.
        /// </summary>
        public static string TextFuelPlanner {
            get {
                return ResourceManager.GetString("TextFuelPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativo.
        /// </summary>
        public static string TextInputAlternative {
            get {
                return ResourceManager.GetString("TextInputAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chegada.
        /// </summary>
        public static string TextInputArrival {
            get {
                return ResourceManager.GetString("TextInputArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga no porão.
        /// </summary>
        public static string TextInputCargoHold {
            get {
                return ResourceManager.GetString("TextInputCargoHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string TextInputDeparture {
            get {
                return ResourceManager.GetString("TextInputDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passageiros (PAX).
        /// </summary>
        public static string TextInputPassengers {
            get {
                return ResourceManager.GetString("TextInputPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título no simulador.
        /// </summary>
        public static string TextInputTitleSimulator {
            get {
                return ResourceManager.GetString("TextInputTitleSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar / Converter Textura (.PTP / .ZIP).
        /// </summary>
        public static string TextInstallConvertLivery {
            get {
                return ResourceManager.GetString("TextInstallConvertLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texturas Instaladas.
        /// </summary>
        public static string TextInstalledLiveries {
            get {
                return ResourceManager.GetString("TextInstalledLiveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem imagem de preview.
        /// </summary>
        public static string TextNoPreviewImage {
            get {
                return ResourceManager.GetString("TextNoPreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passageiros e Carga.
        /// </summary>
        public static string TextPassengersCargo {
            get {
                return ResourceManager.GetString("TextPassengersCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos PRO.
        /// </summary>
        public static string TextPROFeatures {
            get {
                return ResourceManager.GetString("TextPROFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de Voos Salvos.
        /// </summary>
        public static string TextSavedFlightHistory {
            get {
                return ResourceManager.GetString("TextSavedFlightHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo da Aeronave.
        /// </summary>
        public static string TextSelectAircraftModel {
            get {
                return ResourceManager.GetString("TextSelectAircraftModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edição da Livery Selecionada.
        /// </summary>
        public static string TextSelectedLivery {
            get {
                return ResourceManager.GetString("TextSelectedLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aeronave.
        /// </summary>
        public static string TextTableAircraft {
            get {
                return ResourceManager.GetString("TextTableAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativo.
        /// </summary>
        public static string TextTableAlternative {
            get {
                return ResourceManager.GetString("TextTableAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chegada.
        /// </summary>
        public static string TextTableArrival {
            get {
                return ResourceManager.GetString("TextTableArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string TextTableDate {
            get {
                return ResourceManager.GetString("TextTableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir voo do histórico.
        /// </summary>
        public static string TextTableDeleteFlightHistory {
            get {
                return ResourceManager.GetString("TextTableDeleteFlightHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string TextTableDeparture {
            get {
                return ResourceManager.GetString("TextTableDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distância.
        /// </summary>
        public static string TextTableDistance {
            get {
                return ResourceManager.GetString("TextTableDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passageiros.
        /// </summary>
        public static string TextTablePassengers {
            get {
                return ResourceManager.GetString("TextTablePassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustível Total.
        /// </summary>
        public static string TextTableTotalFuel {
            get {
                return ResourceManager.GetString("TextTableTotalFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferramentas.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
