//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AircraftSimManager.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AircraftSimManager.Shared.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert .PTP to .ZIP.
        /// </summary>
        public static string BtnConvertPtpToZip {
            get {
                return ResourceManager.GetString("BtnConvertPtpToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Livery.
        /// </summary>
        public static string BtnRemoveLivery {
            get {
                return ResourceManager.GetString("BtnRemoveLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Flight Plan.
        /// </summary>
        public static string BtnSaveFlightPlan {
            get {
                return ResourceManager.GetString("BtnSaveFlightPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Title.
        /// </summary>
        public static string BtnSaveTitle {
            get {
                return ResourceManager.GetString("BtnSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tool from the top menu to get started..
        /// </summary>
        public static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic calculation of distance and distribution among the aircraft&apos;s fuel tanks..
        /// </summary>
        public static string DescTextAutomaticCalcDistance {
            get {
                return ResourceManager.GetString("DescTextAutomaticCalcDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is currently under development and will be available soon in upcoming updates to Aircraft Sim Manager!.
        /// </summary>
        public static string DescTextComingSoon {
            get {
                return ResourceManager.GetString("DescTextComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize these tanks directly with the aircraft in the simulator via SimConnect!.
        /// </summary>
        public static string DescTextPROFeatures {
            get {
                return ResourceManager.GetString("DescTextPROFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string DialogTitleConfirmDelete {
            get {
                return ResourceManager.GetString("DialogTitleConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Completed.
        /// </summary>
        public static string DialogTitleConversionCompleted {
            get {
                return ResourceManager.GetString("DialogTitleConversionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Failed.
        /// </summary>
        public static string DialogTitleConversionFailed {
            get {
                return ResourceManager.GetString("DialogTitleConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PMDG .PTP file.
        /// </summary>
        public static string DialogTitlePtpSelect {
            get {
                return ResourceManager.GetString("DialogTitlePtpSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogTitleWarning {
            get {
                return ResourceManager.GetString("DialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save converted .ZIP file.
        /// </summary>
        public static string DialogTitleZipSave {
            get {
                return ResourceManager.GetString("DialogTitleZipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing PTP extractor: {0}.
        /// </summary>
        public static string ErrorExecutingExtractor {
            get {
                return ResourceManager.GetString("ErrorExecutingExtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction error: {0}.
        /// </summary>
        public static string ErrorExtraction {
            get {
                return ResourceManager.GetString("ErrorExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed (code {0}): {1}.
        /// </summary>
        public static string ErrorExtractionFailed {
            get {
                return ResourceManager.GetString("ErrorExtractionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation error: {0}.
        /// </summary>
        public static string ErrorInstallation {
            get {
                return ResourceManager.GetString("ErrorInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSFS installation error: {0}.
        /// </summary>
        public static string ErrorMsfsInstallation {
            get {
                return ResourceManager.GetString("ErrorMsfsInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSFS installation via ZIP error: {0}.
        /// </summary>
        public static string ErrorMsfsZipInstallation {
            get {
                return ResourceManager.GetString("ErrorMsfsZipInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PMDG aircraft folder found in specified directory..
        /// </summary>
        public static string ErrorNoPmdgAircraftFound {
            get {
                return ResourceManager.GetString("ErrorNoPmdgAircraftFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No texture folder found in package..
        /// </summary>
        public static string ErrorNoTextureFoldersFound {
            get {
                return ResourceManager.GetString("ErrorNoTextureFoldersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ptp file not found.
        /// </summary>
        public static string ErrorPtpNotFound {
            get {
                return ResourceManager.GetString("ErrorPtpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PtpUnpack.exe executable was not found in the Tools/PtpUnpacker folder..
        /// </summary>
        public static string ErrorUnpackerNotFound {
            get {
                return ResourceManager.GetString("ErrorUnpackerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error compressing to ZIP: {0}.
        /// </summary>
        public static string ErrorZipCompression {
            get {
                return ResourceManager.GetString("ErrorZipCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation via ZIP error: {0}.
        /// </summary>
        public static string ErrorZipInstallation {
            get {
                return ResourceManager.GetString("ErrorZipInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `PMDG Livery File (*.ptp).
        /// </summary>
        public static string FilterPtpFiles {
            get {
                return ResourceManager.GetString("FilterPtpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `ZIP File (*.zip).
        /// </summary>
        public static string FilterZipFiles {
            get {
                return ResourceManager.GetString("FilterZipFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Calculator.
        /// </summary>
        public static string FuelCalculatorTitle {
            get {
                return ResourceManager.GetString("FuelCalculatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liveries Manager.
        /// </summary>
        public static string LiveriesManager {
            get {
                return ResourceManager.GetString("LiveriesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tool from the top menu to get started.
        /// </summary>
        public static string MainTextSelectTool {
            get {
                return ResourceManager.GetString("MainTextSelectTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be blank..
        /// </summary>
        public static string MsgBlankTitleError {
            get {
                return ResourceManager.GetString("MsgBlankTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the livery &apos;{0}&apos;?\n\nThe folder &apos;{1}&apos; will be permanently deleted..
        /// </summary>
        public static string MsgConfirmDeleteLivery {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ZIP file created successfully at:\n{0}.
        /// </summary>
        public static string MsgZipCreatedSuccess {
            get {
                return ResourceManager.GetString("MsgZipCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathSim {
            get {
                return ResourceManager.GetString("PathSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Calculator.
        /// </summary>
        public static string PerformanceCalculator {
            get {
                return ResourceManager.GetString("PerformanceCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Calculator.
        /// </summary>
        public static string PerformanceCalculatorTitle {
            get {
                return ResourceManager.GetString("PerformanceCalculatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (BR).
        /// </summary>
        public static string PortugueseBr {
            get {
                return ResourceManager.GetString("PortugueseBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewImage {
            get {
                return ResourceManager.GetString("PreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files to {0}....
        /// </summary>
        public static string ProgressCopyingFiles {
            get {
                return ResourceManager.GetString("ProgressCopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying textures to {0}....
        /// </summary>
        public static string ProgressCopyingTextures {
            get {
                return ResourceManager.GetString("ProgressCopyingTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating .ZIP file....
        /// </summary>
        public static string ProgressGeneratingZip {
            get {
                return ResourceManager.GetString("ProgressGeneratingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing on aircraft: {0}.
        /// </summary>
        public static string ProgressInstallingAircraft {
            get {
                return ResourceManager.GetString("ProgressInstallingAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering livery in aircraft.cfg....
        /// </summary>
        public static string ProgressRegisteringLivery {
            get {
                return ResourceManager.GetString("ProgressRegisteringLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting unpacking of {0}....
        /// </summary>
        public static string ProgressStartingUnpack {
            get {
                return ResourceManager.GetString("ProgressStartingUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking ZIP {0}....
        /// </summary>
        public static string ProgressUnpackingZip {
            get {
                return ResourceManager.GetString("ProgressUnpackingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating layout.json....
        /// </summary>
        public static string ProgressUpdatingLayout {
            get {
                return ResourceManager.GetString("ProgressUpdatingLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ZIP file generated successfully: {0}.
        /// </summary>
        public static string ProgressZipCreated {
            get {
                return ResourceManager.GetString("ProgressZipCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        public static string SimulatorSelectText {
            get {
                return ResourceManager.GetString("SimulatorSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion completed: {0} created!.
        /// </summary>
        public static string StatusConversionCompleted {
            get {
                return ResourceManager.GetString("StatusConversionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion error: {0}.
        /// </summary>
        public static string StatusConversionError {
            get {
                return ResourceManager.GetString("StatusConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {0} to .ZIP....
        /// </summary>
        public static string StatusConvertingToZip {
            get {
                return ResourceManager.GetString("StatusConvertingToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting installed simulators....
        /// </summary>
        public static string StatusDetectingSimulators {
            get {
                return ResourceManager.GetString("StatusDetectingSimulators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No simulator or path selected..
        /// </summary>
        public static string StatusErrorNoSimOrPath {
            get {
                return ResourceManager.GetString("StatusErrorNoSimOrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to remove livery..
        /// </summary>
        public static string StatusErrorRemovingLivery {
            get {
                return ResourceManager.GetString("StatusErrorRemovingLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save new title in aircraft.cfg..
        /// </summary>
        public static string StatusFailedToSaveTitle {
            get {
                return ResourceManager.GetString("StatusFailedToSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}....
        /// </summary>
        public static string StatusInstallingPackage {
            get {
                return ResourceManager.GetString("StatusInstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} liveries found..
        /// </summary>
        public static string StatusLiveriesFound {
            get {
                return ResourceManager.GetString("StatusLiveriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livery &apos;{0}&apos; installed successfully!.
        /// </summary>
        public static string StatusLiveryInstalledSuccess {
            get {
                return ResourceManager.GetString("StatusLiveryInstalledSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install livery &apos;{0}&apos;. Check the file..
        /// </summary>
        public static string StatusLiveryInstallFailed {
            get {
                return ResourceManager.GetString("StatusLiveryInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livery removed successfully!.
        /// </summary>
        public static string StatusLiveryRemoved {
            get {
                return ResourceManager.GetString("StatusLiveryRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No livery selected for removal..
        /// </summary>
        public static string StatusNoLiverySelectedForDelete {
            get {
                return ResourceManager.GetString("StatusNoLiverySelectedForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No livery selected to change title..
        /// </summary>
        public static string StatusNoLiverySelectedForTitle {
            get {
                return ResourceManager.GetString("StatusNoLiverySelectedForTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No simulator found..
        /// </summary>
        public static string StatusNoSimulatorFound {
            get {
                return ResourceManager.GetString("StatusNoSimulatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing &apos;{0}&apos;....
        /// </summary>
        public static string StatusRemovingLivery {
            get {
                return ResourceManager.GetString("StatusRemovingLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning liveries....
        /// </summary>
        public static string StatusScanningLiveries {
            get {
                return ResourceManager.GetString("StatusScanningLiveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title updated to &apos;{0}&apos; successfully!.
        /// </summary>
        public static string StatusTitleUpdated {
            get {
                return ResourceManager.GetString("StatusTitleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction completed successfully..
        /// </summary>
        public static string SuccessExtraction {
            get {
                return ResourceManager.GetString("SuccessExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed successfully!.
        /// </summary>
        public static string SuccessInstallation {
            get {
                return ResourceManager.GetString("SuccessInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ZIP file created successfully at: {0}.
        /// </summary>
        public static string SuccessZipCreated {
            get {
                return ResourceManager.GetString("SuccessZipCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Distance (NM).
        /// </summary>
        public static string TextCalculatedDistance {
            get {
                return ResourceManager.GetString("TextCalculatedDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string TextComingSoon {
            get {
                return ResourceManager.GetString("TextComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution to the Tanks.
        /// </summary>
        public static string TextDistributionTanks {
            get {
                return ResourceManager.GetString("TextDistributionTanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the .PTP or .ZIP file here to install it.
        /// </summary>
        public static string TextDragFilePtpZip {
            get {
                return ResourceManager.GetString("TextDragFilePtpZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Tank.
        /// </summary>
        public static string TextDrawCenterTank {
            get {
                return ResourceManager.GetString("TextDrawCenterTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Tank.
        /// </summary>
        public static string TextDrawLeftTank {
            get {
                return ResourceManager.GetString("TextDrawLeftTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Tank.
        /// </summary>
        public static string TextDrawRightTank {
            get {
                return ResourceManager.GetString("TextDrawRightTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Route (ICAO).
        /// </summary>
        public static string TextFlightRoute {
            get {
                return ResourceManager.GetString("TextFlightRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Planner.
        /// </summary>
        public static string TextFuelPlanner {
            get {
                return ResourceManager.GetString("TextFuelPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        public static string TextInputAlternative {
            get {
                return ResourceManager.GetString("TextInputAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string TextInputArrival {
            get {
                return ResourceManager.GetString("TextInputArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo in the hold.
        /// </summary>
        public static string TextInputCargoHold {
            get {
                return ResourceManager.GetString("TextInputCargoHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string TextInputDeparture {
            get {
                return ResourceManager.GetString("TextInputDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers (PAX).
        /// </summary>
        public static string TextInputPassengers {
            get {
                return ResourceManager.GetString("TextInputPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in the simulator.
        /// </summary>
        public static string TextInputTitleSimulator {
            get {
                return ResourceManager.GetString("TextInputTitleSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install / Convert Livery (.PTP / .ZIP).
        /// </summary>
        public static string TextInstallConvertLivery {
            get {
                return ResourceManager.GetString("TextInstallConvertLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Liveries.
        /// </summary>
        public static string TextInstalledLiveries {
            get {
                return ResourceManager.GetString("TextInstalledLiveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview image.
        /// </summary>
        public static string TextNoPreviewImage {
            get {
                return ResourceManager.GetString("TextNoPreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers and Cargo.
        /// </summary>
        public static string TextPassengersCargo {
            get {
                return ResourceManager.GetString("TextPassengersCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO Features.
        /// </summary>
        public static string TextPROFeatures {
            get {
                return ResourceManager.GetString("TextPROFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Flight History.
        /// </summary>
        public static string TextSavedFlightHistory {
            get {
                return ResourceManager.GetString("TextSavedFlightHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Model.
        /// </summary>
        public static string TextSelectAircraftModel {
            get {
                return ResourceManager.GetString("TextSelectAircraftModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Livery Edition.
        /// </summary>
        public static string TextSelectedLivery {
            get {
                return ResourceManager.GetString("TextSelectedLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft.
        /// </summary>
        public static string TextTableAircraft {
            get {
                return ResourceManager.GetString("TextTableAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        public static string TextTableAlternative {
            get {
                return ResourceManager.GetString("TextTableAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string TextTableArrival {
            get {
                return ResourceManager.GetString("TextTableArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TextTableDate {
            get {
                return ResourceManager.GetString("TextTableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete flight from history.
        /// </summary>
        public static string TextTableDeleteFlightHistory {
            get {
                return ResourceManager.GetString("TextTableDeleteFlightHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string TextTableDeparture {
            get {
                return ResourceManager.GetString("TextTableDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string TextTableDistance {
            get {
                return ResourceManager.GetString("TextTableDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers.
        /// </summary>
        public static string TextTablePassengers {
            get {
                return ResourceManager.GetString("TextTablePassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fuel.
        /// </summary>
        public static string TextTableTotalFuel {
            get {
                return ResourceManager.GetString("TextTableTotalFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
